on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: 'Version'     
        required: true

name: Test Release

jobs:
  quack-cicd:
    runs-on: ubuntu-latest
    name: Testing Quack CI/CD
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Changelog 
      id: generateChangelog
      uses: kn0pee/quack-cicd@main

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.event.inputs.versionTag }}
        release_name: Release ${{ github.event.inputs.versionTag }}
        body: |
          # Changelog
          ${{ steps.generateChangelog.outputs.changelog }}
        draft: false
        prerelease: false