on: [push]

jobs:
  quack-cicd:
    runs-on: ubuntu-latest
    name: Testing Quack CI/CD
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Changelog 
      id: generateChangelog
      uses: kn0pee/quack-cicd@main

    - name: Print Changelog
      run: echo "${{ steps.generateChangelog.outputs.changelog }}"